//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StartupTimer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StartupTimer.Resources.LocalizationResource", typeof(LocalizationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time is ticking...
        ///Prepare to finish your work!
        ///Left time: {0}.
        /// </summary>
        internal static string AlmostDoneNotify_Format {
            get {
                return ResourceManager.GetString("AlmostDoneNotify.Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup-Timer.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string ContextMenu_Exit_Text {
            get {
                return ResourceManager.GetString("ContextMenu.Exit.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End time: {0}.
        /// </summary>
        internal static string EndTime_Format {
            get {
                return ResourceManager.GetString("EndTime.Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left: {0}.
        /// </summary>
        internal static string LeftTime_Format {
            get {
                return ResourceManager.GetString("LeftTime.Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over time: {0}.
        /// </summary>
        internal static string OverTime_Format {
            get {
                return ResourceManager.GetString("OverTime.Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already worked {0}!.
        /// </summary>
        internal static string OverworkAlert_Format {
            get {
                return ResourceManager.GetString("OverworkAlert.Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time: {0}.
        /// </summary>
        internal static string StartTime_Format {
            get {
                return ResourceManager.GetString("StartTime.Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HH:mm.
        /// </summary>
        internal static string TimeFormat {
            get {
                return ResourceManager.GetString("TimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:{1}min{2}.
        /// </summary>
        internal static string TimeSpan_Format {
            get {
                return ResourceManager.GetString("TimeSpan.Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkTime: {0}.
        /// </summary>
        internal static string WorkTime_Format {
            get {
                return ResourceManager.GetString("WorkTime.Format", resourceCulture);
            }
        }
    }
}
